-- Create the table for booking inquiries
CREATE TABLE contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text NOT NULL,
  event_type text,
  event_date date,
  location text,
  message text
);

-- Enable Row Level Security (RLS)
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Allow public inserts so anyone can submit the contact form
CREATE POLICY "Allow public inserts on contacts" 
ON contacts 
FOR INSERT 
TO public 
WITH CHECK (true);
